#!/bin/bash

# سكربت لتعديل الروابط والأسماء
modify_files() {
    echo "⌭ تعديل الروابط والأسماء ⌭"
    
    # تعديل الروابط والأسماء في جميع الملفات المطلوبة
    for file in *.txt; do
        sed -i '' 's|https://github.com/ZThon-Bot/ZTele.git|https://github.com/QROM1/QROM|g' "$file"
        sed -i '' 's|ZThon-Bot|QROM1|g' "$file"
        sed -i '' 's|https://github.com/ZThon-Back/ZUp|https://github.com/QROM1/QROM|g' "$file"
        sed -i '' 's|ZThon-Back|QROM1|g' "$file"
    done
}

# قم بتشغيل السكربت لتعديل الملفات
modify_files

# الكود الأساسي
_get_ziplink () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL1FST00xL1FST00vYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
}

_get_repolink () {
    echo "aHR0cHM6Ly9naXRodWIuY29tL1FST00xL1FST00uZ2l0" | base64 -d
}

_run_python_code() {
    python3 -c "$1"
}

_run_zedpack_git() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/QROM1/QROM.git"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_zed_git() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="https://github.com/QROM1/QROM.git"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    local zippath="master.zip"
    echo "⌭ جاري تنزيل اكواد السورس ⌭"
    wget -q $(_get_ziplink) -O "$zippath"
    
    echo "⌭ تفريغ البيانات ⌭"
    ZEDPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"

    echo "⌭ يتم التنظيف ⌭"
    rm -rf "$zippath"
    sleep 5
    
    _run_zedpack_git
    cd $ZEDPATH
    _run_zed_git
    
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    
    echo "⌭ جـاري بـدء التشغيل ⌭"
    python3 -m zlzl
}

# تشغيل السكربت الرئيسي
_set_bot