#!/bin/bash

_get_ziplink () {
    echo "https://github.com/Grm808/ztele/archive/master.zip"  # رابط التنزيل لمستودع ztele
}

_get_repolink () {
    echo "https://github.com/Grm808/ztele.git"  # رابط المستودع ztele
}

_run_python_code() {
    python3 -c "$1"
}

_run_zedpack_git() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/Grm808/ztele.git"  # الربط الثابت مع مستودع ztele
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_zed_git() {
    local repolink=$(_get_repolink)  # الآن repolink سيكون رابط مستودع ztele الثابت
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_set_bot () {
    local zippath="master.zip"
    echo "⌭ جاري تنزيل اكواد السورس ⌭"
    wget -q $(_get_ziplink) -O "$zippath"
    
    echo "⌭ تفريغ البيانات ⌭"
    ZEDPATH=$(zipinfo -1 "$zippath" | grep -v "/.")
    unzip -qq "$zippath"

    echo "⌭ يتم التنظيف ⌭"
    rm -rf "$zippath"
    sleep 5
    
    _run_zedpack_git
    cd $ZEDPATH
    _run_zed_git
    
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    
    echo "⌭ جـاري بـدء التشغيل ⌭"
    python3 -m zlzl
}

_set_bot